### PR TITLE
Start special-features section in readme #29

### PR DESCRIPTION
**Pull request by bmag**
Took the liberty to make some changes other than adding the new screen shots. Not done yet (you can see the TODOs), but I have to go for a while.

### CODE REVIEW

**Comment by bmag** [comment]
I think I'm done. I left "Custom String Replacement" section for you to fill, since you probably know it much better than me.

**Comment by justbur** [comment]
Looks good to me. I'll start on the string replacement stuff

**Comment by justbur** [comment]
When you get a chance, can you try to replicate the last screenshot again? I merged in the status-key stuff and made some tweaks. I want to know if you are still getting the last column cutoff. I can't get mine to cutoff columns

**Comment by bmag** [comment]
I'm still getting the cutoff when using side-window. Minibuffer case is ok. Maybe it has something to do with the font or my computer? I'm using Source Code Pro with a size of 13. What's your font? (<kbd>M-x describe-font</kbd> shows your font)

**Comment by justbur** [comment]
Hmm. ok. Weird that it happens in that case with the fit to window stuff.

Source Code Pro, but 12 not 13

**Comment by bmag** [comment]
Also with 12 I can get a cutoff, so it's probably not the font.

**Comment by bmag** [comment]
Look at this: The two lines look like they're the same length, but they're not!
The first line contains 10 arrow characters, the same that which-key uses (I copy-pasted), so it has a length of 10 characters.
The second line contains 10 "a"s and 6 "A"s, so it has a length of 16 characters.
arrow-is-long

Here is my suspicion of what causes the cutoff:
In the case of a bottom side-window, `which-key/max-dimensions` gives `which-key/populate-buffer` the frame's width as the max width. Lets call it `F`. This indicates that the popup window will be able to display F *regular* characters (like "a").
`which-key/populate-buffer` fills the which-key buffer with F characters in each line. But some of these characters are arrow characters, so the lines *look* longer than F characters.
This means that which-key needs a length of more than F *regular* characters in order to be displayed. But, since the frame has a width of only F regular characters, and `fit-window-to-buffer` doesn't increase the frame's size, the result is a cutoff.

You might be able to see the cutoff by changing the frame's size - it only appears for some frame sizes.

**Comment by justbur** [comment]
Oh so you're only seeing it in side window when it's at the bottom? Then
yes that makes sense and there are more arrows when it's displayed
horizontally.

Also it's strange but you arrow looks different from mine. Look at my
screen shots in the readme.

Maybe we should avoid Unicode and use > so it's more consistent?

**Comment by justbur** [comment]
You could test the Unicode theory by trying > for the separator.

**Comment by bmag** [comment]
Maybe Source Code Pro doesn't include those arrows, and we get our arrows from different fallback fonts?

Using ">" does work, though maybe non-monospace fonts could cause the same problem? I guess non-monospace make the characters smaller rather than bigger (like "i") so it won't really be a problem.

The ">" works, but the real arrows looked nicer to me. I don't know what would be a better default - nicer arrows or no cutoff.

**Comment by justbur** [comment]
I could add a padding variable and just tell people to adjust it if this
are getting cutoff. There's not much we can do if people want Unicode
without doing much more complicated calculations that I honestly don't know
how to do

**Comment by justbur** [comment]
What about a bitmap? Is that possible?

**Comment by bmag** [comment]
I have no idea if a bitmap is possible. I think that a padding variable is a good idea, with proper documentation for it and for the option to change the separator I believe it would be enough.

**Comment by justbur** [comment]
Ok I'll go with that. A bitmap make it harder to have the option of Unicode
if you want it

**Pull request merged**
