### PR TITLE
Symbolize special keys

### PR DESCRIPTION
**Pull request by pradyparanjpe**
Use user-assigned symbols (strings) to represent special keys.
If value of ``which-key-special-keys`` is an *alist* of cons cells,
whose cars are special keys such as SPC, TAB,  ...
and the cdrs are symbol strings,
replace the special keys with corresponding symbols.

For backward-compatibility,
if ``which-key-special-keys`` is an ordinary list of keys, old logic of trucation to single character works.

### CODE REVIEW

**Comment by pradyparanjpe** [comment]
I don't know if this feature edit is worth copyright transfer.
I haven't done such an activity before.
I am (obviously) ready to transfer copyright for the edit if necessary and instructed.

**Comment by justbur** [comment]
I believe it will require the copyright transfer given its size, so I will wait to merge it. 

By the way, at least part of this is possible now by specifying a replacement string for the key using `which-key-replacement-alist`. Is it that you want the special key face to apply too?

**Comment by pradyparanjpe** [comment]
> I believe it will require the copyright transfer given its size, so I will wait to merge it.

I got the request form only recently (a few days ago), signed and mailed it back, no reply from GNU FSF since...

**Comment by justbur** [comment]
It can take a while yes. Let me know when you are notified

**Comment by pradyparanjpe** [comment]
> By the way, at least part of this is possible now by specifying a replacement string for the key using which-key-replacement-alist. Is it that you want the special key face to apply too?

Yes, to be treated along with 'special'.

> It can take a while yes. Let me know when you are notified

Got back a mail from FSF with the PDF counter-signed *accepted*. 

How should I share the PDF with you?

**Comment by justbur** [comment]
Great!

There's been a new development in the meantime. which-key was merged into emacs proper. As a result, I am planning to archive this repository and start taking contributions like yours through the standard emacs channels. There are actually two versions of which-key at the moment, the one here and the one that just got merged into the master branch of emacs. 

If possible, would you mind submitting this patch as a bug report to emacs?

**Comment by pradyparanjpe** [comment]
I've never done that before, but I'll try.

**Comment by justbur** [comment]
Thank you.

**Pull request closed without merging**
