### PR TITLE
[WIP] Displaying toplevel keybindings

### PR DESCRIPTION
**Pull request by iqbalansari**
This first iteration, might require more changes before it is ready to merge

### CODE REVIEW

**Comment by justbur** [comment]
@iqbalansari I want to incorporate this feature at least as an option. My issue is that it doesn't fit well with the current way that which-key works, and I want to rethink the design a bit before I do anything. That's all to say, sorry for the delay. It's on my list, but I don't know how quickly I'll get to it.

**Comment by iqbalansari** [comment]
Yes there are some 'not-so-small' changes needed. As I said earlier I was hoping for some feedback for this pull request so that I can improve it and get it into some shape ready to be merged into `which-key`. Feel free to close this, if you do not feel that is happening.

**Comment by justbur** [comment]
ok, when I get a chance I'll push a new branch and add your commits. If you have any questions, don't hesitate to ask.

**Comment by iqbalansari** [comment]
Re-reading your previous comment, I think I completely misunderstood it.

> ok, when I get a chance I'll push a new branch and add your commits.

I don't think that is needed, I can keep pushing changes to my fork till it is ready for merging. Rather let me do this, I will describe the changes/design decisions made in the current iteration along with some explanation. You can provide your feedback based on it. Sounds like a plan?

**Comment by justbur** [comment]
Sure. I'd like to be able to have one key, which can't be `C-h` for this, that pops open the buffer and handles paging for both toplevel bindings and prefix bindings. Getting the toplevel stuff working is one challenge, but I don't know of a nice way at the moment to make this one key available across all possible keymaps without forcing people to provide them, which is really cumbersome. The nice thing about `C-h` is that it's available by default in emacs, but only for prefixed bindings (and so it won't work for toplevel). having two keys, one for toplevel plus `C-h` is a possibility, but not my ideal scenario. 

In terms of the mechanics of getting this to work, I think just focus on getting the functionality right, and then I can look through and help clean the implementation up. The current implementation of which-key could stand to be cleaned up a bit anyway, so I'd like to do this all at once.

**Comment by iqbalansari** [comment]
> but I don't know of a nice way at the moment to make this one key available across all possible keymaps without forcing people to provide them, which is really cumbersome

Perhaps I am missing something but won't adding a key for toplevel popup to `which-key-mode`'s keymap help.

> having two keys, one for toplevel plus C-h is a possibility, but not my ideal scenario.

Or we could use something like <kbd>C-h</kbd><kbd>W</kbd> (I am using this) for the toplevel

> I think just focus on getting the functionality right, and then I can look through and help clean the implementation up. The current implementation of which-key could stand to be cleaned up a bit anyway, so I'd like to do this all at once.

Sounds good, there are some minor things remaining. Let me resolve them and get back to you.

Thanks

**Comment by justbur** [comment]
I like the idea of C-h W or something similar. That seems like as good a
solution as any.

**Comment by justbur** [comment]
@iqbalansari What do you suggest as a key for paging?

**Comment by iqbalansari** [comment]
I kind of forgot about of this pull request sorry about that. As for paging I think we can just 
<kbd>C-h</kbd> for paging, just as we do in other popups. Any particular issues with that?

**Comment by justbur** [comment]
Yes, `C-h` only works the way it does now in the middle of a key sequence. For the top-level bindings there is no active key sequence

**Comment by iqbalansari** [comment]
Would creating a temporary map using `set-transient-map`/`set-temporary-overlay-map` be an option? I think we could use `set-transient-map` for all which-key popups, that would eliminate the issue of user having to manually configure the keybindings for which he wants paging.

**Comment by iqbalansari** [comment]
Here is a summary of changes introduced in above commits (as I had promised and forgot, sorry :pensive:)

- `which-key--get-formatted-key-bindings` has been modified to handle `nil` value of `which-key--current-prefix`. See [which-key.el#L1222-L1269](https://github.com/iqbalansari/emacs-which-key/blob/7dc57bcf36ae7325dd396cc94f98e9f705ff025f/which-key.el#L1222-L1269)
- A lot of keybindings on the toplevel are keyboard translations using `Alt`
keysym which is usually not interesting I have added a customization to not show
these on in the popup. By default these are not shown. See [which-key.el#L257-L264](https://github.com/iqbalansari/emacs-which-key/blob/7dc57bcf36ae7325dd396cc94f98e9f705ff025f/which-key.el#L257-L264) and [which-key.el#L1254-L1256](https://github.com/iqbalansari/emacs-which-key/blob/7dc57bcf36ae7325dd396cc94f98e9f705ff025f/which-key.el#L1254-L1256)
- Keybindings of the form `<some-key>` are ignored, since most of them are mouse bindings, also headings for keybindings are removed explicitly since I could see a way to handle them using regexp alone (my regex-fu isn't that great). See [which-key.el#L1232-L1249](https://github.com/iqbalansari/emacs-which-key/blob/7dc57bcf36ae7325dd396cc94f98e9f705ff025f/which-key.el#L1232-L1249) and [which-key.el#L1258-L1259](https://github.com/iqbalansari/emacs-which-key/blob/7dc57bcf36ae7325dd396cc94f98e9f705ff025f/which-key.el#L1258-L1259)
- A top level command was added to view toplevel keybindings [which-key.el#L553-L555](https://github.com/iqbalansari/emacs-which-key/blob/7dc57bcf36ae7325dd396cc94f98e9f705ff025f/which-key.el#L553-L555)

**Comment by justbur** [comment]
> Would creating a temporary map using set-transient-map/set-temporary-overlay-map be an option? I think we could use set-transient-map for all which-key popups, that would eliminate the issue of user having to manually configure the keybindings for which he wants paging.

It would probably work for the toplevel bindings, but would be complicated for prefix commands I think.

> Some keybindings on toplevel are described by describe-buffer-keybindings as a .. z some-command, this means characters a to z are all bound to some-command how should we handle such cases? Should we simply display a..z in which-key popup or expand each character in range to a separate entry in the pop. I am leaning towards the former. Your thoughts?

I like the former as a default, and possibly a user option for the latter.

> Keybinding for paging the toplevel popup, I was planning to use set-transient-map/set-temporary-overlay-map. What do you think?

Definitely worth a try. I think the toplevel bindings with have to be handled differently than the others. If you find the transient map works well we can explore using it for the rest of which-key

Thanks for the work. I think this will be useful when it's finished

**Comment by iqbalansari** [comment]
> It would probably work for the toplevel bindings, but would be complicated for prefix commands I think.

You are right, it turns out I was completely off the mark about using transient keymap for all popups.

> I like the former as a default, and possibly a user option for the latter.

Makes sense. How about we delay implement second option until someone asks for it?

> Definitely worth a try. I think the toplevel bindings with have to be handled differently than the others. If you find the transient map works well we can explore using it for the rest of which-key

As I said earlier I missed an important detail when I was thinking of using `set-transient-map` for all keymaps, so you are right. I feel we can avoid the additional complexity of `set-transient-map` and just bind a key in `which-key-map`, which would go to next page if popup is visible. Optionally it can call whatever is bound to globally that key when a popup is not visible. 

> Thanks for the work. I think this will be useful when it's finished

The pleasure is mine :smile:. I know this is taking a bit longer than it should, that is because I have a bit busy lately.

**Comment by justbur** [comment]
>  How about we delay implement second option until someone asks for it?

Sounds good

> As I said earlier I missed an important detail when I was thinking of using set-transient-map for all keymaps, so you are right. I feel we can avoid the additional complexity of set-transient-map and just bind a key in which-key-map, which would go to next page if popup is visible. Optionally it can call whatever is bound to globally that key when a popup is not visible.

Unless I'm missing something, a transient keymap should work fine for toplevel bindings and I think it's the best choice.

> I know this is taking a bit longer than it should, that is because I have a bit busy lately.

Not a problem. Take your time

**Comment by iqbalansari** [comment]
> Unless I'm missing something, a transient keymap should work fine for toplevel bindings and I think it's the best choice.

Yes, it works. I just wanted to be sure you are okay with the (small) additional complexity it introduces. I have pushed a commit that implements the paging for toplevel popup. It uses whatever `which-key-paging-key` is bound to for paging, additionally if `which-key-use-C-h-for-paging` is non-nil <kbd>C-h</kbd> is also used for paging. Please take a look.

**Comment by justbur** [comment]
Nice! I just played with it a little, but it works as I would want it to. Do you have anything else that you wanted to do with this? I haven't gone through the code carefully or tested different cases yet. 

I did notice this though. It's on the last page of my toplevel bindings. Maybe there's some reason to include these ranges for people?

unicode-keys

**Comment by justbur** [comment]
On the last point, let's just ignore the `self-insert-command` bindings. I don't think there's any value to seeing them

**Comment by iqbalansari** [comment]
> On the last point, let's just ignore the self-insert-command bindings. I don't think there's any value to seeing them

Done, I was going to suggest the same thing.

> Do you have anything else that you wanted to do with this

One thing that I would like to do is to improve sorting of keys, for example <kbd>F2</kbd> appears after <kbd>F4</kbd> but that can be done separately. Other than that I think I am done in terms of features. If you are okay with code, I can squash this into a single commit (if you prefer).

**Comment by justbur** [comment]
I don't mind a lot of commits. On the sorting, I guess this must be the first time I've seen a lot of function keys together. I can fix that, unless you have a quick fix for it

**Comment by iqbalansari** [comment]
I do not have a quick fix in mind for the sorting issue. Since you are okay with the current commits, I think we can merge this :+1: . Thanks for your patience.

**Comment by justbur** [comment]
Fixed the sort order 65f0755

I'll review and merge as soon as I get the time. Thanks

**Comment by iqbalansari** [comment]
> I'll review and merge as soon as I get the time. Thanks

Sounds good

**Comment by justbur** [comment]
Actually could you rebase on master?

**Comment by iqbalansari** [comment]
Done

**Comment by justbur** [comment]
:+1: I made a few style changes, including renaming the main function to `which-key-show-top-level` otherwise it looks great. Thanks for the contribution.

**Comment by justbur** [comment]
I don't have time to do the readme now, but it's on my list

**Comment by iqbalansari** [comment]
> I don't have time to do the readme now, but it's on my list

Sounds good. If I get some time, I might update it as well.

**Pull request merged**
