### PR TITLE
Speed up which-key--maybe-replace

### LINKED ISSUE #226: Lots of time spent inside which-key--maybe-replace
I think this is a which-key issue and not specifically related to spacemacs as it happens in multiple different major modes (ruby and org).

I found [this](https://github.com/syl20bnr/spacemacs/issues/12455) but it is not related as I am on the most recent spacemacs develop and I have tried with the most recent which-key as well.

Output from profiler:
```
- timer-event-handler                                            4120  74%
 - apply                                                         4119  74%
  - which-key--update                                            4068  73%
   - which-key--create-buffer-and-show                           4068  73%
    - which-key--get-bindings                                    3761  68%
     - which-key--format-and-replace                             3713  67%
      - which-key--maybe-replace                                 3658  66%
         which-key--match-replacement                              50   0%
       + which-key--get-pseudo-binding                             35   0%
      + which-key--propertize-description                          17   0%
      + kbd                                                        14   0%
      + which-key--propertize                                       1   0%
        which-key--extract-key                                      1   0%
        which-key--maybe-add-docstring                              1   0%
      + which-key--propertize-key                                   1   0%
     + which-key--get-current-bindings                             45   0%
     + sort                                                         1   0%
    + which-key--show-page                                        173   3%
    + which-key--create-pages                                     133   2%
  + sp-show--pair-function                                         11   0%
```

#### Description :octocat:
emacs gets really slugging when hitting a key that triggers which-key and it takes several seconds for the menu to show during which time emacs is maxing out a core.

#### Reproduction guide :beetle:
- Start Emacs
- Fiddle around in either org mode or ruby (might be others too)

*Observed behaviour:* :eyes: :broken_heart:
emacs gets really slugging when hitting a key that triggers which-key and it takes several seconds for the menu to show during which time emacs is maxing out a core.

*Expected behaviour:* :heart: :smile:
which-key to react instantly

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: peter_develop (rev. 8916788d5)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
((auto-completion :variables auto-complete-idle-delay 0.1 auto-completion-complete-with-key-sequence "jk" auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'cycle)
 better-defaults
 (dash :variables dash-docs-docset-newpath
       (cond
        ((spacemacs/system-is-linux)
         (expand-file-name "Zeal/Zeal/docsets"
                           (getenv "XDG_DATA_HOME")))
        ((spacemacs/system-is-mac)
         (expand-file-name "Library/ApplicationSupport/Dash/DocSets"
                           (getenv "HOME")))))
 evil-commentary
 (finance :variables ledger-use-iso-dates t)
 (geolocation :variables geolocation-enable-automatic-theme-changer nil geolocation-enable-location-server t geolocation-enable-weather-forecast t)
 graphviz ivy multiple-cursors
 (mu4e :variables mu4e-account-alist nil mu4e-mu-home
       (expand-file-name "mu"
                         (getenv "XDG_CACHE_HOME"))
       mu4e-maildir
       (expand-file-name "mail"
                         (getenv "XDG_CACHE_HOME"))
       mu4e-enable-async-operations nil mu4e-enable-notifications t mu4e-use-maildirs-extension nil)
 pandoc pdf plantuml
 (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'vterm shell-scripts-backend 'lsp)
 (templates :variables templates-use-default-templates t)
 theming treemacs
 (git :variables git-magit-status-fullscreen t)
 pass
 (spell-checking :variables enable-flyspell-auto-completion nil flyspell-issue-welcome-flag nil ispell-local-dictionary "en" ispell-program-name
                 (or
                  (getenv "ASPELL")
                  "/run/current-system/sw/bin/aspell")
                 ispell-really-aspell t spell-checking-enable-by-default
                 (spacemacs/system-is-linux)
                 spell-checking-enable-auto-dictionary nil)
 version-control ansible nginx terraform yaml c-c++ cmake
 (crystal :variables crystal-enable-auto-format t)
 dap emacs-lisp
 (haskell :variables flycheck-haskell-runghc-command
          '("stack" "--verbosity" "silent" "runghc" "--no-ghc-package-path" "--" "--ghc-arg=-i")
          haskell-completion-backend 'lsp haskell-enable-hindent t haskell-process-type 'stack-ghci haskell-stylish-on-save t)
 (lsp :variables lsp-auto-guess-root t lsp-navigation 'both lsp-ui-doc-use-webkit nil lsp-ui-flycheck-enable t lsp-ui-sideline-enable t)
 nixos
 (python :variables python-enable-yapf-format-on-save t)
 (ruby :variables ruby-backend 'lsp ruby-enable-enh-ruby-mode nil ruby-highlight-debugger-keywords t ruby-test-runner 'rspec ruby-version-manager nil)
 shell-scripts
 (sql :variables sql-auto-indent t sql-capitalize-keywords t)
 typescript
 (windows-scripts :variables dos-prefer-bat-mode nil)
 ruby-on-rails gtags
 (restclient :variables restclient-use-org nil)
 syntax-checking csv html
 (markdown :variables markdown-live-preview-engine 'eww)
 (org :variables org-enable-hugo-support t org-enable-jira-support t org-enable-reveal-js-support t org-enable-trello-support
      (spacemacs/system-is-linux)
      org-export-backends
      '(ascii html icalendar latex md)
      org-reveal-note-key-char nil org-use-speed-commands nil)
 (speartail :variables speartail-auto-save-interval nil)
 nix peter)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2

### PR DESCRIPTION
**Pull request by rgrinberg**
The first optimization is avoiding the intermediate list created by
append. Instead we just iterate over the two lists in turn

The second opimitization occurs where
which-key-allow-multiple-replacements is nil, in which case we can stop
the iteration once we've found a replacement

Fixes #226

### CODE REVIEW

**Comment by rgrinberg** [comment]
I've had another look at this and we can make this thing fly if we introduce another setting or change the meaning of this one. The vast majority of bindings are by key. If we had a way to lookup a key specific binding using `assq`, the perf would be great.

Perhaps we should add an additional variable? Or add a special `'by-key` key inside `which-key-replacement-alist` that would have this assoc list? Kind of like how we handle major modes.

**Comment by justbur** [comment]
Originally I had thought about making a hash table/cache, but then I didn't think it was worth it because no one had reported performance issues for the longest time. 

I'm actually a little surprised that you get a big improvement with this code. I'm curious now whether it's the append or the breaking out of the loop that makes the bigger difference. 

I'm thinking now that just doing the hash-table thing might be the most straightforward, but I'm open to suggestions. Only problem would be worrying about updating the replacements on the fly, but I don't think that's a big deal.

**Comment by rgrinberg** [comment]
> I'm actually a little surprised that you get a big improvement with this code. I'm curious now whether it's the append or the breaking out of the loop that makes the bigger difference.

Hard to say. I bet breaking out of the loop is better for consistent for performance, but removing extra allocation probably reduces sporadic GC lag. Both offered a measurable improvement however.

> I'm thinking now that just doing the hash-table thing might be the most straightforward, but I'm open to suggestions. Only problem would be worrying about updating the replacements on the fly, but I don't think that's a big deal.

Sure. A hash table sound fine to me. Any look up operation that is implemented using a primitive is probably going to work well enough. The question is, how do we preserve the backwards compatibility?

**Comment by rgrinberg** [comment]
By the way, perhaps it makes sense to discuss how to rework this feature separately? The current PR gives a considerable speed up without any downsides, so I think it's best to just make it available to users.

**Comment by justbur** [comment]
That makes sense to me. 

There is one potential complication though, and sorry for not thinking of this earlier. Because which-key is on gnu elpa, technically you would need to have copyright papers filed with the FSF. [Here is an explanation](https://github.com/abo-abo/swiper/blob/master/CONTRIBUTING.org#copyright-assignment). Maybe you have already done this?

**Comment by justbur** [comment]
Alternatively, there might be a way to keep this under 15 lines, which would make the copyright assignment unnecessary.

**Comment by rgrinberg** [comment]
I’ve already signed these papers when I contributed to another elpa project. Do I need to do it for which-key as well?

**Comment by justbur** [comment]
Oh great. No, I believe you only need to do it once. I'll go ahead and merge this then

**Comment by justbur** [comment]
That's weird. I pushed the commit to master, but github didn't close the pr. Did something change recently?

**Comment by justbur** [comment]
Oh, maybe it's because I had to rebase... Anyway, it's merged. Thanks

**Pull request closed without merging**
