### PR TITLE
Better window sizes

### LINKED ISSUE #19: BUG: which-key window not wide enough
Using these settings:
```elisp
(setq which-key-popup-type 'side-window
      which-key-side-window-location 'right
      which-key-side-window-max-width 90)
```
Results in a which-key window that isn't wide enough for the lines in the which-key buffer. The "empty" lines contain spaces, and each such line is actually the continuation of the previous line (Spacemacs makes it look like two different lines, but in the buffer it's a single line).
which-key-not-wide-enough

This is the actual content of the which-key buffer. Notice the cursor is at the bottom left corner of the text:
which-key-actual-buffer

I will debug this later, but I suspect we may have a slight miscommunication about `which-key/show-popup` and `which-key/popup-max-dimensions`. As I understand it, the ACT-POPUP-DIM argument to `show-popup` specifies the width and the height of the popup window as follows:
- width: the length of each line in which-key buffer, or the length of the longest line in which-key buffer. Length is the same as "number of columns". `show-popup` should take care of calculating necessary width to accommodate for fringes, margins, scroll bars, etc.
- height: the number of lines in which-key buffer.

Assuming all lines are of the same length, ACT-POPUP-DIM should be equivalent to:
```elisp
(with-current-buffer which-key-buffer-name
  (save-excursion
    (goto-char (point-max))
    (cons (line-number-at-pos) (current-column))))
```

Concerning `popup-max-dimensions`, as I understand it, the function should return the maximal height and width that `show-popup` can handle. So the following should always be true:
```elisp
(and (<= (car argument-to-show-popup) (car popup-max-dimensions-return-value))
     (<= (cdr argument-to-show-popup) (car popup-max-dimensions-return-value)))
```

Please share what meaning you meant those parameters to have, so we can agree on a single meaning and fix this issue.

### PR DESCRIPTION
**Pull request by bmag**
This doesn't fix #19 completely, but it's still something.
Also allow `which-key-side-window-max-width` and `which-key-side-window-max-height` to be percentages (floating-point number between 0 and 1).
I don't know why the commit references #22, I probably got confused.

### CODE REVIEW

**Comment by justbur** [comment]
Nice! Thank you.

What if you broke out those utility functions into a separate package, like window-size.el or something?

**Comment by justbur** [comment]
I'm getting this problem again

side-window-extra-space

**Comment by justbur** [comment]
Also, since it's along the same lines could you look into why the minibuffer cuts off the text here? There's no mode-line, and it seems like the max-height is still wrong

minibuffer-cutoff

**Comment by bmag** [comment]
I've changed it to use `fit-window-to-buffer` again. Seems to work in GUI emacs, but in the terminal for some reason the window is still too narrow. Maybe you could improve/fix it?

As for the wrong max-height, that's probably an off-by-one mistake some where.

I've been thinking for a while about a library package for window sizes and locations, but I'm not there yet.

**Comment by justbur** [comment]
Hm. I haven't been trying this in the terminal much at all. I'll look into it later. 

I don't think so. I tried this and the heights agree:

```
(setq tmr (run-at-time 2 1 (lambda () (message "hgt: %s max-dims: %s"
                                               (window-height (get-buffer-window which-key--buffer))
                                               (which-key/side-window-max-dimensions))) ))
```

For that kind of library I'd think you could build it out gradually, since it's mostly just a bunch of relatively simple calculations that you need to get right once.

**Pull request merged**
